In [1]:
import seaborn as sns
import datetime as dt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

%matplotlib inline

In [4]:
df = pd.read_csv('train.csv', usecols=['Id', 'YrSold', 'LotArea', 'SalePrice', 'MSSubClass', 'MSZoning', 'Street','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','SaleType','SaleCondition'])

df.head()

# с чем можно работать
#df = pd.get_dummies(df, columns=['MSZoning', 'Street','Alley','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition'])

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,Typ,Attchd,RFn,TA,TA,Y,2008,WD,Normal,208500
1,2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,Typ,Attchd,RFn,TA,TA,Y,2007,WD,Normal,181500
2,3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,Typ,Attchd,RFn,TA,TA,Y,2008,WD,Normal,223500
3,4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,Typ,Detchd,Unf,TA,TA,Y,2006,WD,Abnorml,140000
4,5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,Typ,Attchd,RFn,TA,TA,Y,2008,WD,Normal,250000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 43 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotArea          1460 non-null int64
Street           1460 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinType2     1422 non-null object
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
KitchenQual      1460 non-null object
Functional       1460 non-null object
GarageType       1379 non-null object
GarageFinish     1379 non-null object
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: int64(5), object(38)
memory usage: 490.5+ KB

In [14]:
df_train = df.drop(['Id'], axis=1)

In [15]:
# кодируем категориальные признаки

df_train = pd.get_dummies(df_train, columns=['MSZoning','LandSlope','Street', 'LotShape', 'LandContour', 'Utilities','LotConfig', 'Neighborhood','Condition1', 'Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st', 'Exterior2nd', 'MasVnrType','ExterQual','ExterCond', 'Foundation', 'BsmtQual','BsmtCond', 'BsmtExposure', 'BsmtFinType1','BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir','Electrical', 'KitchenQual','Functional','GarageType','GarageFinish', 'GarageQual','GarageCond','PavedDrive', 'SaleType','SaleCondition'])

In [16]:
# Заполняем пропуски средними значениями по столбцам
df_train.fillna(df_train.mean())

,MSSubClass,LotArea,YrSold,SalePrice,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,LandSlope_Gtl,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,8450,2008,208500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1,20,9600,2007,181500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
2,60,11250,2008,223500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
3,70,9550,2006,140000,0,0,0,1,0,1,...,0,0,0,1,1,0,0,0,0,0
4,60,14260,2008,250000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
5,50,14115,2009,143000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
6,20,10084,2007,307000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
7,60,10382,2009,200000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
8,50,6120,2008,129900,0,0,0,0,1,1,...,0,0,0,1,1,0,0,0,0,0
9,190,7420,2008,118000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
10,20,11200,2008,129500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
11,60,11924,2006,345000,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
12,20,12968,2008,144000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
13,20,10652,2007,279500,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
14,20,10920,2008,157000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
15,45,6120,2007,132000,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
16,20,11241,2010,149000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
17,90,10791,2006,90000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
18,20,13695,2008,159000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
19,20,7560,2009,139000,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
20,60,14215,2006,325300,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
21,45,7449,2007,139400,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
22,20,9742,2008,230000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
23,120,4224,2007,129900,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
24,20,8246,2010,154000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
25,20,14230,2009,256300,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
26,20,7200,2010,134800,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
27,20,11478,2010,306000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
28,20,16321,2006,207500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
29,30,6324,2008,68500,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60,21930,2006,192140,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1431,120,4928,2009,143750,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1432,30,10800,2007,64500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1433,60,10261,2008,186500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1434,20,17400,2006,160000,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1435,20,8400,2008,174000,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
1436,20,9000,2007,120500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1437,20,12444,2008,394617,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1438,20,7407,2010,149700,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1439,60,11584,2007,197000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1440,70,11526,2008,191000,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1441,120,4426,2008,149300,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1442,60,11003,2009,310000,0,1,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1443,30,8854,2009,121000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1444,20,8500,2007,179600,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1445,85,8400,2007,129000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1446,20,26142,2010,157900,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1447,60,10000,2007,240000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1448,50,11767,2007,112000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1449,180,1533,2006,92000,0,0,0,0,1,1,...,0,0,0,1,1,0,0,0,0,0
1450,90,9000,2009,136000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1451,20,9262,2009,287090,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1452,180,3675,2006,145000,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1453,20,17217,2006,84500,0,0,0,1,0,1,...,0,0,0,1,1,0,0,0,0,0
1454,20,7500,2009,185000,0,1,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1455,60,7917,2007,175000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1456,20,13175,2010,210000,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1457,70,9042,2010,266500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1458,20,9717,2010,142125,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1459,20,9937,2008,147500,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0

In [17]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 238 entries, MSSubClass to SaleCondition_Partial
dtypes: int64(4), uint8(234)
memory usage: 379.3 KB

In [18]:
y = df_train['SalePrice']
df_test_preproc=df_train.drop(['SalePrice'], axis=1)
from sklearn.model_selection import train_test_split
X, X_test, y, y_test = train_test_split(df_test_preproc, y, test_size=0.33, random_state=42)

In [19]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, classification_report

C:\Users\Ildar\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

model = DecisionTreeClassifier()                    # инициализируем модель
model.fit(X, y)                                     # обучаем модель
predict = model.predict(X_test)                     # делаем предсказание
predict_proba1 = model.predict_proba(X_test)

In [30]:
df_test_1 = pd.read_csv('test.csv', usecols=['Id', 'YrSold', 'LotArea','MSSubClass', 'MSZoning', 'Street','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','SaleType','SaleCondition'])
df_test_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 42 columns):
Id               1459 non-null int64
MSSubClass       1459 non-null int64
MSZoning         1455 non-null object
LotArea          1459 non-null int64
Street           1459 non-null object
LotShape         1459 non-null object
LandContour      1459 non-null object
Utilities        1457 non-null object
LotConfig        1459 non-null object
LandSlope        1459 non-null object
Neighborhood     1459 non-null object
Condition1       1459 non-null object
Condition2       1459 non-null object
BldgType         1459 non-null object
HouseStyle       1459 non-null object
RoofStyle        1459 non-null object
RoofMatl         1459 non-null object
Exterior1st      1458 non-null object
Exterior2nd      1458 non-null object
MasVnrType       1443 non-null object
ExterQual        1459 non-null object
ExterCond        1459 non-null object
Foundation       1459 non-null object
BsmtQual         1415 non-null object
BsmtCond         1414 non-null object
BsmtExposure     1415 non-null object
BsmtFinType1     1417 non-null object
BsmtFinType2     1417 non-null object
Heating          1459 non-null object
HeatingQC        1459 non-null object
CentralAir       1459 non-null object
Electrical       1459 non-null object
KitchenQual      1458 non-null object
Functional       1457 non-null object
GarageType       1383 non-null object
GarageFinish     1381 non-null object
GarageQual       1381 non-null object
GarageCond       1381 non-null object
PavedDrive       1459 non-null object
YrSold           1459 non-null int64
SaleType         1458 non-null object
SaleCondition    1459 non-null object
dtypes: int64(4), object(38)
memory usage: 478.8+ KB

In [22]:
# кодируем категориальные признаки

df_test_1 = pd.get_dummies(df_test_1, columns=['MSZoning','LandSlope','Street', 'LotShape', 'LandContour', 'Utilities','LotConfig', 'Neighborhood','Condition1', 'Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st', 'Exterior2nd', 'MasVnrType','ExterQual','ExterCond', 'Foundation', 'BsmtQual','BsmtCond', 'BsmtExposure', 'BsmtFinType1','BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir','Electrical', 'KitchenQual','Functional','GarageType','GarageFinish', 'GarageQual','GarageCond','PavedDrive', 'SaleType','SaleCondition'])

In [23]:
# Заполняем пропуски средними значениями по столбцам
df_test_1.fillna(df_test_1.mean())

,Id,MSSubClass,LotArea,YrSold,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,LandSlope_Gtl,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,11622,2010,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1,1462,20,14267,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
2,1463,60,13830,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
3,1464,60,9978,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
4,1465,120,5005,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
5,1466,60,10000,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
6,1467,20,7980,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
7,1468,60,8402,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
8,1469,20,10176,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
9,1470,20,8400,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
10,1471,120,5858,2010,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
11,1472,160,1680,2010,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0
12,1473,160,1680,2010,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
13,1474,160,2280,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
14,1475,120,2280,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
15,1476,60,12858,2010,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
16,1477,20,12883,2010,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
17,1478,20,11520,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
18,1479,20,14122,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
19,1480,20,14300,2010,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
20,1481,60,13650,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
21,1482,120,7132,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
22,1483,20,18494,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
23,1484,120,3203,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
24,1485,80,13300,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
25,1486,60,8577,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
26,1487,60,17433,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
27,1488,20,8987,2010,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
28,1489,20,9215,2010,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1
29,1490,20,10440,2010,0,1,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2890,30,7030,2006,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1430,2891,50,9060,2006,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1431,2892,30,12366,2006,1,0,0,0,0,1,...,0,0,0,1,1,0,0,0,0,0
1432,2893,190,9000,2006,1,0,0,0,0,1,...,0,0,0,1,1,0,0,0,0,0
1433,2894,50,8520,2006,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1434,2895,120,5748,2006,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
1435,2896,120,3842,2006,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
1436,2897,20,23580,2006,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1437,2898,90,8385,2006,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1438,2899,20,9116,2006,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1439,2900,80,11080,2006,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1440,2901,20,50102,2006,0,0,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
1441,2902,20,8098,2006,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1442,2903,20,13618,2006,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1443,2904,20,11577,2006,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1444,2905,20,31250,2006,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
1445,2906,90,7020,2006,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1446,2907,160,2665,2006,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1447,2908,20,10172,2006,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1448,2909,90,11836,2006,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1449,2910,180,1470,2006,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1450,2911,160,1484,2006,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1451,2912,20,13384,2006,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1452,2913,160,1533,2006,0,0,0,0,1,1,...,0,0,0,1,1,0,0,0,0,0
1453,2914,160,1526,2006,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1454,2915,160,1936,2006,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1455,2916,160,1894,2006,0,0,0,0,1,1,...,0,0,0,1,1,0,0,0,0,0
1456,2917,20,20000,2006,0,0,0,1,0,1,...,0,0,0,1,1,0,0,0,0,0
1457,2918,85,10441,2006,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
1458,2919,60,9627,2006,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0

In [25]:
df_id=df_test_1['Id']

In [27]:
df_test_1=df_test_1.drop(['Id'], axis=1)

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

predict_test = model.predict(df_test_1)

ValueError: Number of features of the model must match the input. Model n_features is 237 and input n_features is 221

In [29]:
df_test_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Columns: 221 entries, MSSubClass to SaleCondition_Partial
dtypes: int64(3), uint8(218)
memory usage: 344.9 KB

In [33]:
# Запишем все по файлам для загрузки на Kaggle
df_id=pd.read_csv('test.csv', usecols=['Id'])

df_predict = pd.DataFrame(predict_test)
df_pr=df_predict[0]
# Объединяем таргет и ID в датафрейм
df_predict1=pd.concat([df_id, df_pr], axis=1)
df_predict1.columns = ['Id', 'SalePrice']
df_predict1.to_csv('predict1.csv', sep=',', encoding='utf-8', index=False)

In [70]:
#df_test_1 = df_test_1.fillna(df_test_1.mean())

In [74]:
                 # делаем предсказание

ValueError: Number of features of the model must match the input. Model n_features is 289 and input n_features is 270